In [1]:
import numpy as np # (pip install numpy first)

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[4.0,5.0,6.0],[7.0,8.0,9.0]])
print(b)

[[4. 5. 6.]
 [7. 8. 9.]]


In [4]:
c = np.array([3,2,1], dtype='int16')

In [5]:
# Get Shape
a.shape

(3,)

In [6]:
b.shape

(2, 3)

In [7]:
# Get Dimension
a.ndim

1

In [8]:
# Get Type
a.dtype

dtype('int32')

In [9]:
c.dtype

dtype('int16')

In [10]:
# Get Size
a.itemsize

4

In [11]:
c.itemsize

2

In [12]:
# Get total size
a.nbytes

12

### Accessing/Changing specific elements, rows, columns etc.

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Get a specific element [r, c]
a[1, 4]

12

In [15]:
a[1, -2]

13

In [16]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [18]:
# startindex:endindex:stepsize
a[0, 1:6:2]

array([2, 4, 6])

In [19]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [20]:
a[:, 2] = 1

a[:, 3] = [1, 2]
print(a)

[[ 1  2  1  1  5  6  7]
 [ 8  9  1  2 12 20 14]]


In [21]:
# 3d example
d =  np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# Get specific element
d[0,1,1]

4

In [23]:
# Replace
d[:,1,:] = [[1,1],[2,2]]

In [24]:
d

array([[[1, 2],
        [1, 1]],

       [[5, 6],
        [2, 2]]])

### Initializing Different Types of Arrays

In [25]:
# All 0s matrix
np.zeros(5)
# np.zeros((2,3))
# np.zeros((2,3,3))

array([0., 0., 0., 0., 0.])

In [26]:
# All 1s matrix
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [27]:
# Any other number
np.full((2,2), 20)

array([[20, 20],
       [20, 20]])

In [28]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [29]:
# Random decimal numbers
np.random.rand(4,2)
# np.random.random_sample(a.shape)

array([[0.45927046, 0.82848606],
       [0.19974306, 0.24493529],
       [0.52842705, 0.01707536],
       [0.25741454, 0.83391019]])

In [30]:
# Random Integer values
np.random.randint(-4,7, size=(3,3)) # numbers from -4 up to 7(6)

array([[-2,  0,  2],
       [ 0,  4,  0],
       [ 5,  5, -4]])

In [31]:
# The Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [33]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
# Copying arrays
a = np.array([1,2,3])
c = a
c[0] = 99 # a[0] also changed the value

print(a)

b = a.copy()
b[0] = 100

print(a)

[99  2  3]
[99  2  3]


### Mathematics

In [35]:
a = np.array([1,2,3,4])

# Elementwise addition
a + 2

array([3, 4, 5, 6])

In [36]:
# Elementwise subtraction
a - 2

array([-1,  0,  1,  2])

In [37]:
a * 2

array([2, 4, 6, 8])

In [38]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [39]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [40]:
a ** 2

array([ 1,  4,  9, 16])

In [41]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra

In [42]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [43]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [44]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.min(stats)
# np.min(stats, axis=1)

1

In [46]:
np.max(stats)

6

In [47]:
np.sum(stats)

21

### Reorganizing Arrays

In [48]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
# Vertically stacking vectors(matrices)
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])
# np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Load Data from File

In [61]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  11,  21,  33, 233,  56,  78,  89,  43,   5,   7,   8,  46,
          2,  74,   2,  12,  14],
       [  3,   7,   8,  46, 766,  17,  22,  13,  45,  18,  42,  77,  65,
         73,  50,  20,  71,   5],
       [  4,   7,   3,  11, 345,  70,  26,  18,   5,   9,  15,  36,   8,
         98,   6,  12,  47,  28]])

### Boolean Masking and Advanced Indexing

In [57]:
filedata >= 50

array([[False, False, False, False,  True,  True,  True,  True, False,
        False, False, False, False, False,  True, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False,  True,  True,  True,  True, False,  True, False],
       [False, False, False, False,  True,  True, False, False, False,
        False, False, False, False,  True, False, False, False, False]])

In [58]:
# Grabs values that are greater than 50
filedata[filedata > 50]

array([233,  56,  78,  89,  74, 766,  77,  65,  73,  71, 345,  70,  98])

In [59]:
# Indexing with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,8]]

array([2, 4, 9])

In [60]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True,  True,  True, False,
       False, False,  True,  True,  True,  True, False,  True, False])

In [62]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [63]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [64]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True,  True,  True, False,
        False, False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False,  True,  True,  True, False, False,  True, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False,  True, False, False, False, False]])

In [66]:
(~((filedata > 50) & (filedata < 100))) # the opposite

array([[ True,  True,  True,  True,  True, False, False, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False, False, False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True]])